name: push to dockerhub
on:
  push:
    branches: [ main ]
jobs:
  push:
    environment: dockerhub
    runs-on: ubuntu-latest     
    steps:
      - 
        name: Fetch repository
        uses: actions/checkout@main
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx   # for arm build
        uses: docker/setup-buildx-action@v1  
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: dbryanjohnson/starlink-monitor:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      -
        name: ARM build
        id: docker_build_arm
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.arm32
          push: true
          tags: dbryanjohnson/starlink-monitor:arm32
